version: "3.1"

services:
  db:
    image: mysql:5.7.27
    environment:
      MYSQL_DATABASE: change
      MYSQL_ROOT_PASSWORD: changethis
    ports:
      - 4000:3306
    volumes:
      - ./dbdata:/var/lib/mysql:delegated
#borrar, solo para produccion
  myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PASSWORD: changethis
      PMA_USER: root
      PMA_PORT: 3306
    ports:
      - 8001:80
#
  app:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ./src/composer/cache:/root/.composer/cache:delegated
      - ./src/basic:/app:delegated
    environment:
      DB_DATABASE: change
      DB_PASSWORD:  changethis
      DB_HOST: db
      PHP_USER_ID: 1000
      PRODUCCION: 1
    ports:
      - 8000:80
  
